### ISSUE TITLE
comentarios avance 3 y README

### ISSUE THREAD

**Issue by AliciaMstt** [Mariette-VJ/TrabajoFinal_BioInvRepro_Mariette#2]
Tu avance 3 está muy bien aunque tendrá algo de penalización por la fecha de entrega.

Tu README tmb está muy bien, solo recomiendo que en párrafos como el siguiente:

'predict_otus' folder, as well as the first output file of the second script, containing only archaea species abundances. Second and third output file of second script will be located inside output folder and inside images folder within, respectively.

Pongas el la ruta de los directorios `marcados como código`. Así mismo, cuando tengas el nombre completo de los archivos output, ponlos, no namás digas un archivo txt que tendrá tal cosa.

**Comment by Mariette-VJ** [comment]
Entiendo perfecto lo de la penalización. Los cambios recomendados se han hecho al README 

Muchas gracias
